
"""Configuration settings for ScriptVoice."""

import os

# File paths
PROJECTS_FILE = "projects.json"
AUDIO_FOLDER = "audio_output"
TEMP_FOLDER = "temp"

# IONOS AI Model Hub settings (primary)
IONOS_API_TOKEN = os.getenv("IONOS_API_TOKEN", "eyJ0eXAiOiJKV1QiLCJraWQiOiJkZDZkNWExYS00NDY0LTQ0MGEtYjJhMC05NjY0Y2IzNDZiNDYiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJpb25vc2Nsb3VkIiwiaWF0IjoxNzQ4NDgwMjk5LCJjbGllbnQiOiJVU0VSIiwiaWRlbnRpdHkiOnsiaXNQYXJlbnQiOmZhbHNlLCJjb250cmFjdE51bWJlciI6MzM5NzEwMzMsInJvbGUiOiJvd25lciIsInJlZ0RvbWFpbiI6Imlvbm9zLmNvbSIsInJlc2VsbGVySWQiOjEsInV1aWQiOiI3YmNiNzg4MS1hZDMxLTQxMDgtOGI3Zi0wOGIyNjdiYTI0ZWUiLCJwcml2aWxlZ2VzIjpbIkRBVEFfQ0VOVEVSX0NSRUFURSIsIlNOQVBTSE9UX0NSRUFURSIsIklQX0JMT0NLX1JFU0VSVkUiLCJNQU5BR0VfREFUQVBMQVRGT1JNIiwiQUNDRVNTX0FDVElWSVRZX0xPRyIsIlBDQ19DUkVBVEUiLCJBQ0NFU1NfUzNfT0JKRUNUX1NUT1JBR0UiLCJCQUNLVVBfVU5JVF9DUkVBVEUiLCJDUkVBVEVfSU5URVJORVRfQUNDRVNTIiwiSzhTX0NMVVNURVJfQ1JFQVRFIiwiRkxPV19MT0dfQ1JFQVRFIiwiQUNDRVNTX0FORF9NQU5BR0VfTU9OSVRPUklORyIsIkFDQ0VTU19BTkRfTUFOQUdFX0NFUlRJRklDQVRFUyIsIkFDQ0VTU19BTkRfTUFOQUdFX0xPR0dJTkciLCJNQU5BR0VfREJBQVMiLCJBQ0NFU1NfQU5EX01BTkFHRV9ETlMiLCJNQU5BR0VfUkVHSVNUUlkiLCJBQ0NFU1NfQU5EX01BTkFHRV9DRE4iLCJBQ0NFU1NfQU5EX01BTkFHRV9WUE4iLCJBQ0NFU1NfQU5EX01BTkFHRV9BUElfR0FURVdBWSIsIkFDQ0VTU19BTkRfTUFOQUdFX05HUyIsIkFDQ0VTU19BTkRfTUFOQUdFX0tBQVMiLCJBQ0NFU1NfQU5EX01BTkFHRV9ORVRXT1JLX0ZJTEVfU1RPUkFHRSIsIkFDQ0VTU19BTkRfTUFOQUdFX0FJX01PREVMX0hVQiIsIkNSRUFURV9ORVRXT1JLX1NFQ1VSSVRZX0dST1VQUyIsIkFDQ0VTU19BTkRfTUFOQUdFX0lBTV9SRVNPVVJDRVMiXX0sImV4cCI6MTc1NjI1NjI5OX0.MWVvOpvWZFsqQSegbv2IowICHBug2IJODqMk9qSKLRkbzBpLf63JtXwhC8jLDzSFUBgg40mXvMMo0s0-AAcalDeCAKDMccWZYzsKuKVfalTAsh0EGhc8aegs53zXX75MYx02pBddAb2pXrQ96sOknoyffekiM0vufIkD39Rj92gXAUStt7BPjTor1eCqs48BPvHjVojdE_tVJZg5kYAq5f_nAKTT3yDj1_2CQQdtrUZVI_FY8yl5Q_0DyN4oASNDsALhIv2wr49V2dvb9EB-AqIO1TndgkyZxH66Isnz2zJ2BA1tWgSMGTnXAQXNQ5O8qXq0gq97xDoqMjVEk9TahA")
IONOS_MODEL_NAME = "meta-llama/Meta-Llama-3.1-8B-Instruct"
IONOS_ENDPOINT = "https://openai.inference.de-txl.ionos.com/v1"
IONOS_CHAT_URL = "https://inference.de-txl.ionos.com/models/meta-llama/Meta-Llama-3.1-8B-Instruct/predictions"
IONOS_IMAGE_URL = "https://openai.inference.de-txl.ionos.com/v1/images/generations"

# API Keys (with fallbacks to OpenAI)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
ELEVENLABS_API_KEY = os.getenv("ELEVENLABS_API_KEY", "")

# Default settings
DEFAULT_TTS_SPEED = 1.0
DEFAULT_ENHANCEMENT_TYPE = "dialogue"

# Voice settings for TTS
DEFAULT_VOICE_ID = "9BWtsMINqrJLrRacOk9x"  # Aria voice
DEFAULT_MODEL_ID = "eleven_multilingual_v2"

# File upload limits
MAX_FILE_SIZE_MB = 10
ALLOWED_IMAGE_EXTENSIONS = ['.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff']

# Vector database settings
VECTOR_DB_CHUNK_SIZE = 500
VECTOR_DB_CHUNK_OVERLAP = 50

# Model settings
SENTENCE_TRANSFORMER_MODEL = "all-MiniLM-L6-v2"
